config/routes.rb
Rails.application.routes.draw do
 
  resources :gyms
  resources :fitness_coaches
  resources :workout_types
  resources :training_sessions
  resources :members
  resources :games

 get '/login', to: 'sessions#new'
 post 'login', to: 'sessions#create'
 delete '/logout', to: 'sessions#destroy'
 
 
 
 
 
  # get 'workout_types/index'
  # get 'workout_types/show'
  # get 'workout_types/create'
  # get 'workout_types/new'
  # get 'workout_types/edit'
  # get 'workout_types/update'
  # get 'workout_types/delete'
  # get 'training_sessions/index'
  # get 'training_sessions/show'
  # get 'training_sessions/create'
  # get 'training_sessions/new'
  # get 'training_sessions/edit'
  # get 'training_sessions/update'
  # get 'training_sessions/delete'
  # get 'fitness_coaches/index'
  # get 'fitness_coaches/show'
  # get 'fitness_coaches/create'
  # get 'fitness_coaches/new'
  # get 'fitness_coaches/edit'
  # get 'fitness_coaches/update'
  # get 'fitness_coaches/delete'
  # get 'members/index'
  # get 'members/show'
  # get 'members/create'
  # get 'members/new'
  # get 'members/edit'
  # get 'members/update'
  # get 'members/delete'
  # get 'gyms/index'
  # get 'gyms/show'
  # get 'gyms/create'
  # get 'gyms/new'
  # get 'gyms/edit'
  # get 'gyms/update'
  # get 'gyms/delete'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
    has_many :training_sessions
    has_many :fitness_coaches, through: :training_sessions
    belongs_to :gym 
    has_secure_password

    validates :name, uniqueness: { scope: :gym, message: "Error: You already belong to this gym!"}

    def sess_mem
        #### on member show page, show number of sessions ####
        self.training_sessions.count
    end

    def self.most_liked_member
        ### on members index it shows who has most sessions ###
        Member.all.max_by {|member| member.sess_mem}
    end

    def liked_coach
        self.training_sessions.map {|session| session.fitness_coach.name}
        #array of coaches theyve worked out with
    end

    def self.best_pair
        ### on members and/or coaches index to show the most often paired group ###
        Member.all.map  do |member| 
            " #{member.name} works out with #{member.liked_coach}"
        end
    end



    def self.the_wisest 
        ### on member index this shows the oldest member of the gym ###
        count = 0
        wisest =[]
        Member.all.each do |member|
            if member.age > count 
                count = member.age
                wisest = member
            end
        end
        "#{wisest.name} is our wisest member."
    end

    def self.young_buck
       ### on member index this shows the youngest member of the gym ###
       buck = Member.all.each{|member| member.age}.min
       "#{buck.name} is our youngest buck with some muscle to fill in!"
    end

end

# tried to make a form to push a button to keep score of workouts done
# <%= form_with url: "/games", method: "post" do %>
#     <%= label_tag :workout, "Type workout to complete a workout!" %><br><br>
#     <%= text_field_tag :workout,  %><br><br>
#     <% = submit_tag "Do Workout"  %>
#     <% end %>

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :current_user, only: [:show]
  before_action :not_logged_in, only: [:show]


  def index
    @members = Member.all
  end

  def show
    @score = session[:score]
    # byebug
    # @member = Member.find(params[:id])
  end

  def new
    @gyms = Gym.all
    @member = Member.new
  end

  def create
    @member = Member.create(member_params)
      if @member.valid?
        session[:id] = @member.id
        session[:score] = 0
        redirect_to @member
      else
        flash[:errors] = @member.errors.full_messages
        redirect_to new_member_path
      end
  end

  def edit
    @gyms = Gym.all
    @member = Member.find(params[:id])
  end

  def update
    # byebug
    @member = Member.find(params[:id])
    @member.update({
            name: params[:member][:name],
            age: params[:member][:age],
            gym_id: params[:member][:gym_id],
        })
        if @member.valid?
          redirect_to member_path(@member)
        else
          flash[:errors] = @member.errors.full_messages
          redirect_to new_member_path
        end
  end

  def destroy
    @member = Member.find(params[:id])
    @member.destroy
    redirect_to members_path
  end

  private
  def member_params
    params.require(:member).permit(:name, :age, :gym_id, :password, :password_confirmation)
  end

end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/delete.html.erb
<h1>Members#delete</h1>
<p>Find me in app/views/members/delete.html.erb</p>

app/views/members/edit.html.erb
<h1>Edit <%="#{@member.name}" %> </h1>
<hr>

<ul style= "list-style-type: none; color: red; padding-left: 0; font-weight: bold;">
    <li>
        <%= flash[:errors] %>
    </li>
</ul>

<%= form_with model: @member do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br><br>
    <%= f.label :age %>
    <%= f.number_field :age %><br><br>
    <%= f.label :gym_id %>
    <%= f.collection_select(:gym_id, @gyms, :id, :name) %><br><br>
    <%= f.submit %>
    <% end %>
    

app/views/members/index.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Members</title>
</head>
    
<body>

<banner>
<h1>Members</h1>
    <nav>
        <ul>
            <li><%= link_to "Fitness Coaches", '/fitness_coaches', method: :get %></li>
            <li class="active"><%= link_to "Members", '/members', method: :get %></li>
            <li><%= link_to "Gyms", '/gyms', method: :get %></li>
            <li><%= link_to "Work Outs", '/workout_types', method: :get %></li>
            <li><%= link_to "Training Sessions", '/training_sessions', method: :get %></li>
        </ul>
    </nav>
</banner>

<div class="sidenav">
<h2 style="color: rgb(8, 189, 23); text-align: center; font-size: 1.2em;">Our Members:</h2>
    <% @members.each do |member| %>
        <li>
            <%= link_to member.name, member %>
        </li>
    <% end %>
</div>

<div class="main">
<h2>--Fitness Coach Shoutouts--</h2>

<p> Our member with the most sessions: <br>
<%= Member.most_liked_member.name %> <p>


<%= Member.the_wisest %> <br>
<br>

<%= Member.young_buck %>

<%= button_to "create member", '/members/new', method: :get %>
</div>
</body>
    
</html>

app/views/members/new.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Title of the document</title>
</head>

<body>

<banner>
<h1>New Members Sign Up</h1>
    <nav>
        <ul>
            <li><%= link_to "Fitness Coaches", '/fitness_coaches', method: :get %></li>
            <li><%= link_to "Members", '/members', method: :get %></li>
            <li><%= link_to "Gyms", '/gyms', method: :get %></li>
            <li><%= link_to "Work Outs", '/workout_types', method: :get %></li>
            <li><%= link_to "Training Sessions", '/training_sessions', method: :get %></li>
        </ul>
    </nav>
</banner>

<ul style= "list-style-type: none; color: red; padding-left: 0; font-weight: bold;">
    <li>
        <%= flash[:errors] %>
    </li>
</ul>

<%= form_with model: @member do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br><br>
    <%= f.label :age %>
    <%= f.number_field :age %><br><br>
    <%= f.label :gym_id %>
    <%= f.collection_select(:gym_id, @gyms, :id, :name) %><br><br>
    <%= f.label :Password %>
    <%= f.password_field :password %> <br><br>
    <%= f.label :Password_Confirmation %>
    <%= f.password_field :password_confirmation %> <br><br>
    <%= f.submit %>
    <% end %>
</body>

</html>
    
 

app/views/members/show.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Member Info</title>
</head>

<body>

<banner>
<h1><%= @member.name %></h1>

    <nav>
        <ul>
            <li><%= link_to "Fitness Coaches", '/fitness_coaches', method: :get %></li>
            <li><%= link_to "Members", '/members', method: :get %></li>
            <li><%= link_to "Gyms", '/gyms', method: :get %></li>
            <li><%= link_to "Work Outs", '/workout_types', method: :get %></li>
            <li><%= link_to "Training Sessions", '/training_sessions', method: :get %></li>
        </ul>
    </nav>
</banner>

<div>
    <h2> Age </h2>
    <ul style= "list-style-type: none;">
        <li>
            <%= @member.age %>
        </li>
    </ul>
</div>

<div>
    <h2> Gym </h2>
    <ul style= "list-style-type: none;">
        <%= @member.gym.name %>
    </ul>
</div>

<div>
    <h2> Fitness Coaches </h2>
    <ul style= "list-style-type: none;">
        <% @member.fitness_coaches.each do |coach| %>
            <li>
                <%= link_to coach.name, coach %>
            </li>
        <% end %>
    </ul>
</div>

<div>
    <h2> Training Sessions </h2>
    <ul style="list-style-type: none; ">
        <li>
            <%= @member.name %> has <%= @member.sess_mem %> sessions. 
        </li>
    </ul>
</div>


<div>
    <% @member.training_sessions.each do |session| %>
        <ul style="list-style-type: none;">
            <li style= "text-decoration: none;">
                <%= link_to session.workout_type.name, session.workout_type %>  workout with <%= link_to session.fitness_coach.name, session.fitness_coach %> 
            </li>
        </ul>
    <% end %>
</div>

<br>
<p> Score: <%= @score %></p>
<%= form_with url: "/games", method: "post" do %>
    <%= label_tag :workout, "Wanna workout?" %><br><br>
    <%= text_field_tag :workout %> hint: type "workout"<br><br>
    <%= submit_tag "Workout" %><br><br>
  <% end %>
<br>
<%= button_to "create training session", new_training_session_path, method: :get %>
<br>
<%= button_to "delete", @member, method: :delete %>
<br>
<%= button_to "edit", edit_member_path, method: :get %>
<br>
<%= button_to "log out", '/logout', method: :delete %>
<br>

</body>

</html>